config/routes.rb
Rails.application.routes.draw do

  root to: "homepage#index"
  
  resources :projects do 
    resources :boards
  end
  
  post "/board/:board_id/items", to: "board_items#create", as: "board_items"  
  
  devise_for :users, path: 'auth', 
  path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
  unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, controllers: { registrations: "registrations" }
  
  get "/dashboard", to: "dashboard#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :project
  has_many :board_items
  
  validates :name, length: { in: 3..20 }
  validates :description, length: { in: 3..20 }
end

app/models/board_item.rb
class BoardItem < ApplicationRecord
  belongs_to :board
  validates :description, length: { in: 2..20 }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :boards
  validates :name, length: { in: 3..20 }
  validates :description, length: { in: 3..20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_items_controller.rb
class BoardItemsController < ApplicationController
  
  before_action :authenticate_user!
  
  
  def create
    
     board = Board.find(params[:board_id])
     @board_items = board.board_items.new(board_items_params)
    
     if @board_items.save()
       respond_to do |format|
         format.json { render json: { status: :created, board_items: board.board_items.all } }
       end
     else
       respond_to do |format|
         format.json { render json: { status: :false } }
       end
     end

  end
  
  def board_items_params
    params.require(:board_item).permit( :description, :board_id)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  

  # GET /boards
  # GET /boards.json
  def index
    @project = Project.find(params[:project_id])
    @boards = @project.boards
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @project = Project.find(params[:project_id])
    @board = Board.new()
    
  end

  # GET /boards/1/edit
  def edit
    @project = Project.find(params[:project_id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @project = Project.find(params[:project_id])
    @board = @project.boards.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to project_boards_path(@project), notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: project_board_path(@project) }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to project_boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :description, :project_id)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  
  def index
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def after_sign_up_path_for(resource)
    '/dashboard' # Or :prefix_to_your_route
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_items_helper.rb
module BoardItemsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: [@project,@board], local: true) do |form| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% @board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form'%>

<%= link_to 'Show', project_boards_path(@project,@board) %> |
<%= link_to 'Back', project_boards_path(@project) %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>


 <div style="display:flex; flex-wrap: wrap;">

    <% @boards.each do |board| %>
      <div style="display:flex; margin: 20px; flex-wrap: wrap; flex-direction: column;">
		<span><%= link_to 'Destroy', project_board_path(board.project,board), method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <span><%= board.name %></span>
        <span><%= board.description %></span>
       <!-- <span><%= link_to 'Edit', edit_project_board_path(board.project,board) %></span>!-->

		
		<div class="board_items">
			<%= link_to "DODELAT", board_items_path(board)%>
		  <label for=""></label><input type="text" onClick="add_item(this,'<%= board_items_url(board) %>','<%= board.id %>');" />
		  <ul id="board_items-<%=board.id%>">
			  <% board.board_items.each do |item| %>
			     <li><%= item.description%></li>
			  <% end %>
		  	
		  </ul>
		</div>
		
      </div>
    <% end %>
 </div>

<br>

<%= link_to 'New Board', new_project_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', project_boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @board.description %>
</p>

<%= link_to 'Edit', edit_project_board_path(@board.project,@board) %> |
<%= link_to 'Back', project_boards_path(@board.project) %>

app/views/dashboard/index.html.erb
dashboard


<br>

přehled projektů

app/views/homepage/index.html.erb
<br>
<%= link_to "Projects", projects_path()%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  
	  <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>
	  


	  <% if user_signed_in? %>
	    <%=link_to "Odhlasit se", destroy_user_session_url, method: :delete%>
		
		<%else%>
		
  	 	 <%= link_to "Přihlásit", new_user_session_url %>

  	 	 <%= link_to "Registrace", new_user_registration_url%>
	  <%end%>
	  
	  
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
 
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>



<br>

<h1 id="tady">Tady bude přehled boardů</h1>

<br>
<%= link_to 'New Board', new_project_board_path(@project)%>